name: CI/CD Pipeline

on:
  push:
    branches: [ main ] 
  pull_request:
    branches: [ main ]
    types: [opened, synchronize]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm test
      - name: Lint
        run: npx eslint src
      - name: Build
        run: npm run build
      - name: Bump version and push tag
        if: github.ref == 'refs/heads/main' && github.event_name == 'pull_request'
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          WITH_V: true
 
